### ISSUE TITLE
Shortcut keys do not work in OSX Client

### ISSUE THREAD

**Issue by RouteTable** [TechxArtisanStudio/Openterface_MacOS#4]
For the shortcut keys, it says it should be the globe (function key) + F to activate full screen mode. This doesn't seem to work. 

Actually, none of the shortcut keys work, including Paste (command + V ), Minimize (command + M), Quit (command + Q).

If I click Edit/Paste, it does function.... just not using command + V.....

Build 1.2(7)

**Comment by ling3ye** [comment]
Hello, thanks for the feedback!

This issue has been resolved in a new version, the latest version is Build 1.3(19) . May I ask if you have joined internal TestFlight?
Since the process of releasing an app for external testing is quite cumbersome and requires a video review, we tend to release a lot of minor changes in the internal TestFlight.

Regarding the copy and paste shortcut not working, is it because the target device is another system, for example in windows the copy hotkey might be control + c .
