### ISSUE TITLE
F11, F12 keypresses are not properly passed to the target

### ISSUE THREAD

**Issue by SebastianOsinski** [TechxArtisanStudio/Openterface_MacOS#8]
F11:
When pressed, F11 is not passed to the target at all. If default "Show Desktop" MacOS keyboard shortcut is enabled, it is activated on the host. If it's disabled, nothing happens.

F12:
When F12 is pressed, target receives F11 press instead of F12.

Tested on:
Host: macOS Sonoma 14.4.1/Openterface 1.2(7)
Target: Raspberry Pi 4B with RaspberryPi OS

**Comment by youyoubilly** [comment]
On macOS, pressing F11 shows the macOS desktop by default, instead of passing the F11 key to the app and the target computer. To fix this, the "Show Desktop" function needs to be unbound from F11. Here’s how:

1. Go to System Settings.
2. Select Desktop & Dock.
3. Scroll down and click the "Shortcuts…" button.
4. Find "Show Desktop" and set it to the hyphen (-) at the bottom of the dropdown list.
5. This change will let the F11 key pass through to your application on the target computer.

![iShot_2024-05-20_19 26 39](https://github.com/TechxArtisanStudio/Openterface_MacOS/assets/54311293/ea1a218f-7032-45c1-a456-a5c2ebf2b87c)

**Comment by SebastianOsinski** [comment]
@youyoubilly Doesn't work for me in the scenario I described. It still does not pass to the target and F12 is passed as F11.

**Comment by ling3ye** [comment]
Preview of new features in the latest version
![image](https://github.com/TechxArtisanStudio/Openterface_MacOS/assets/15604327/348ff14a-119e-4536-b95c-9716b337a538)
